services:
  redis:
    image: redis:7-alpine
    container_name: telemetry_redis
    ports:
      - "6379:6379"
    networks:
      - telemetry_net

  kafka:
    image: apache/kafka:latest
    container_name: telemetry_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - telemetry_net

  postgres:
    image: postgres:15-alpine
    container_name: telemetry_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=telemetry_user
      - POSTGRES_PASSWORD=telemetry_password
      - POSTGRES_DB=telemetry_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - telemetry_net

  db_migrations:
    image: migrate/migrate:v4.15.2
    container_name: telemetry_migrations
    volumes:
      - ./cmd/migrations:/migrations
    command: -path=/migrations -database "postgres://telemetry_user:telemetry_password@postgres:5432/telemetry_db?sslmode=disable" up
    depends_on:
      - postgres
    networks:
      - telemetry_net

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    image: telemetry-collector:latest
    container_name: telemetry_collector
    environment:
      - KAFKA_ADDR=kafka:29092
    depends_on:
      - kafka
    networks:
      - telemetry_net

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    image: telemetry-analyzer:latest
    container_name: telemetry_analyzer
    ports:
      - "2112:2112"
    environment:
      - KAFKA_URL=kafka:29092
      - REDIS_ADDR=redis:6379
      - DATABASE_URL=postgres://telemetry_user:telemetry_password@postgres:5432/telemetry_db?sslmode=disable
    depends_on:
      - kafka
      - redis
      - postgres
      - db_migrations
    networks:
      - telemetry_net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: telemetry-api:latest
    container_name: telemetry_api
    ports:
      - "50051:50051"
    environment:
      - REDIS_ADDR=redis:6379
      - DATABASE_URL=postgres://telemetry_user:telemetry_password@postgres:5432/telemetry_db?sslmode=disable
    depends_on:
      - redis
      - postgres
      - db_migrations
    networks:
      - telemetry_net

  prometheus:
    image: prom/prometheus:latest
    container_name: telemetry_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - analyzer
    networks:
      - telemetry_net

  grafana:
    image: grafana/grafana:latest
    container_name: telemetry_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - telemetry_net

volumes:
  pgdata:

networks:
  telemetry_net:
    driver: bridge
